### ISSUE TITLE
builder isn't registered by Sphinx 1.6

### ISSUE THREAD

**Issue by jcb91** [rtfd/readthedocs-sphinx-ext#27]
So I've been using the readthedocs sphinx builder to make a travis build of documentation for https://github.com/ipython-contrib/jupyter_contrib_nbextensions. However, from sphinx 1.6, I get failures saying the builder has not been registered (see, e.g. [this one](https://travis-ci.org/ipython-contrib/jupyter_contrib_nbextensions/jobs/233272752#L603-L623)). I assume this is something to do with sphinx switching to using pkg_resources entry points (https://github.com/sphinx-doc/sphinx/pull/2803), so maybe it'd be worth adopting that for future use? Alternatively, if you could give me some hint on how to ensure the builders are registered by adding something to `conf.py`, that'd be super helpful...

**Comment by jcb91** [comment]
traceback from the travis build is

```
Traceback (most recent call last):
  File "/home/travis/build/ipython-contrib/jupyter_contrib_nbextensions/.tox/docs_build/lib/python3.4/site-packages/sphinx/registry.py", line 70, in preload_builder
    entry_point = next(entry_points)
StopIteration
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/build/ipython-contrib/jupyter_contrib_nbextensions/.tox/docs_build/lib/python3.4/site-packages/sphinx/cmdline.py", line 305, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/travis/build/ipython-contrib/jupyter_contrib_nbextensions/.tox/docs_build/lib/python3.4/site-packages/sphinx/application.py", line 198, in __init__
    self.preload_builder(buildername)
  File "/home/travis/build/ipython-contrib/jupyter_contrib_nbextensions/.tox/docs_build/lib/python3.4/site-packages/sphinx/application.py", line 297, in preload_builder
    self.registry.preload_builder(self, name)
  File "/home/travis/build/ipython-contrib/jupyter_contrib_nbextensions/.tox/docs_build/lib/python3.4/site-packages/sphinx/registry.py", line 73, in preload_builder
    ' through entry point') % name)
sphinx.errors.SphinxError: Builder name readthedocs not registered or available through entry point
Sphinx error:
Builder name readthedocs not registered or available through entry point
```

**Comment by stsewd** [comment]
RTD uses the extension with sphinx > 1.7. You may want to see https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl for how rtd uses the extension (that file is added to all `conf.py` files).

**Comment by mscuthbert** [comment]
Were you able to solve the problem?  Currently forcing Sphinx <1.7

**Comment by stsewd** [comment]
You need this in your `conf.py` file

```python
extensions = [
    'readthedocs_ext.readthedocs',
]
```
