### ISSUE TITLE
Extension doesn't build on py3

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs-sphinx-ext#8]
Package nilsimsa is failing on python3, seems they are adding support here still.

```
% pip install .
Unpacking /Users/anthony/tmp/pynilsimsa/readthedocs-sphinx-ext
  Running setup.py (path:/var/folders/0z/3wz65d6s1dvcrqnhxqd1kvjr0000gn/T/pip-obq66495-build/setup.py) egg_info for package from file:///Users/anthony/tmp/pynilsimsa/readthedocs-sphinx-ext

Downloading/unpacking requests (from readthedocs-sphinx-ext==0.5.3)
  Downloading requests-2.7.0-py2.py3-none-any.whl (470kB): 470kB downloaded
Downloading/unpacking nilsimsa (from readthedocs-sphinx-ext==0.5.3)
  Downloading nilsimsa-0.3.6.tar.gz (276kB): 276kB downloaded
  Running setup.py (path:/private/var/folders/0z/3wz65d6s1dvcrqnhxqd1kvjr0000gn/T/pip_build_anthony/nilsimsa/setup.py) egg_info for package nilsimsa
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/private/var/folders/0z/3wz65d6s1dvcrqnhxqd1kvjr0000gn/T/pip_build_anthony/nilsimsa/setup.py", line 5, in <module>
        from version import get_git_version
      File "/private/var/folders/0z/3wz65d6s1dvcrqnhxqd1kvjr0000gn/T/pip_build_anthony/nilsimsa/version.py", line 78
        except Exception, exc:
                        ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/private/var/folders/0z/3wz65d6s1dvcrqnhxqd1kvjr0000gn/T/pip_build_anthony/nilsimsa/setup.py", line 5, in <module>

    from version import get_git_version

  File "/private/var/folders/0z/3wz65d6s1dvcrqnhxqd1kvjr0000gn/T/pip_build_anthony/nilsimsa/version.py", line 78

    except Exception, exc:

                    ^

SyntaxError: invalid syntax

----------------------------------------
Cleaning up...
```

**Comment by agjohnson** [comment]
Additionally, there are some more python3 issues with this library, #10 addresses those.
